version: '3.8'

services:  
  react_app: 
    container_name: react_app
    image: react_app
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # docker run -i
    tty: true #docker run -t
    volumes:
      - appVolume:/usr/src/react_app 
      - nodeModuleVolume:/react_app/node_modules
volumes: 
  appVolume:
    driver: local
  nodeModuleVolume: 
    driver: local
